### ISSUE TITLE
Quality filtering removing major part of my read even at 0 

### ISSUE THREAD

**Issue by smartise** [dbeisser/Natrix2#27]
hello, thanks again for you work on this amazing pipeline. 
I am trying to process my CO1 metabarcoding amplification of eDNA sample using your pipeline. However I find that the pychopper is removing an extremely high amount of sequence even when the quality score is set to 0

```
rule quality_filtering:
    input: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/fastq/barcode01_A_1.tmp
    output: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq
    jobid: 12
    reason: Missing output files: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq; Input files updated by another job: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/fastq/barcode01_A_1.tmp
    wildcards: sample=barcode01, unit=A
    threads: 40


                cat /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/fastq/barcode01_A_1.tmp | chopper --quality 0 --minlength 600 --maxlength 900 --headcrop 0 --tailcrop 0 --threads 40 > /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq
                
Activating conda environment: /mnt/ebe/Natrix2/.snakemake/conda/f6c0cf70
Kept 75770 reads out of 96754 reads
Removing temporary output file /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/fastq/barcode01_A_1.tmp.
[Fri Dec 20 11:09:53 2024]
Finished job 12.
3 of 35 steps (9%) done
Select jobs to execute...

[Fri Dec 20 11:09:53 2024]
rule pychop:
    input: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/custom_primers.fasta, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/config_primers.txt
    output: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/output/normal/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/reports/normal/barcode01_A_R1.pdf, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/unclassified/normal/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/rescued/normal/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/unclassified/normal/barcode01_A_R1_length_out.fastq
    jobid: 11
    reason: Missing output files: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/output/normal/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/unclassified/normal/barcode01_A_R1.fastq; Input files updated by another job: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/custom_primers.fasta, /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/config_primers.txt
    wildcards: sample=barcode01, unit=A
    threads: 40


                pychopper -m edlib -b /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/custom_primers.fasta -Q 0 -z 600 -l /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/unclassified/normal/barcode01_A_R1_length_out.fastq -c /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/config_primers.txt -r /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/reports/normal/barcode01_A_R1.pdf -u /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/unclassified/normal/barcode01_A_R1.fastq -w /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/rescued/normal/barcode01_A_R1.fastq -t 40 /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/pychopper/output/normal/barcode01_A_R1.fastq;
                
Activating conda environment: /mnt/ebe/Natrix2/.snakemake/conda/42e83c31
Using kit: PCS109
Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
WARNING: No reverse complement for Y found, returning argument.WARNING: No reverse complement for Y found, returning argument.WARNING: No reverse complement for W found, returning argument.WARNING: No reverse complement for H found, returning argument.WARNING: No reverse complement for R found, returning argument.WARNING: No reverse complement for V found, returning argument.WARNING: No reverse complement for R found, returning argument.WARNING: No reverse complement for V found, returning argument.WARNING: No reverse complement for W found, returning argument.Counting fastq records in input file: /mnt/ebe/AmpliconSequencingONT/sard2_eDNA_natrix_CO1_test/results/quality_filtering/barcode01_A_R1.fastq
Total fastq records in input file: 75770
Tuning the cutoff parameter (q) on 10060 sampled reads (13.2%) passing quality filters (Q >= 0.0).
Optimizing over 30 cutoff values.
```
and here is my config .yaml for the filtering part 

```
#Quality check and primer removal for Nanopore
nanopore:
        quality_filt: 0 # Minimum Phred quality score.
        min_length: 600 # Minimum length of reads.
        max_length: 900 # Maximum length of reads.
        head_trim: 0 # Trim N nucleotides from the start of reads.
        tail_trim: 0 # Trim N nucleotides from the end of reads.
        pychopper: TRUE # Boolean that indicates if pychopper should be used for reorientation, trimming and quality check of reads, if not done before.
        pychopqual: 0 #Minimum mean Q-score base quality for pychopper (default 7).
        racon : 3
```
thanks a lot for you help
cheers
